FROM mcr.microsoft.com/dotnet/sdk:8.0

WORKDIR /src

COPY . .

RUN dotnet tool install --global dotnet-ef --version 8.*

ENV PATH="$PATH:/root/.dotnet/tools"

RUN dotnet restore "Integration.Api/Integration.Api.csproj"

ENTRYPOINT ["dotnet", "ef", "database", "update", "--project", "Integration.Api"]